#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UsdaMigration
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="UsdaFood4")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::UsdaMigration.Properties.Settings.Default.UsdaFood4ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ABBREV> ABBREVs
		{
			get
			{
				return this.GetTable<ABBREV>();
			}
		}
		
		public System.Data.Linq.Table<WEIGHT> WEIGHTs
		{
			get
			{
				return this.GetTable<WEIGHT>();
			}
		}
		
		public System.Data.Linq.Table<FOOD_DE> FOOD_DEs
		{
			get
			{
				return this.GetTable<FOOD_DE>();
			}
		}
		
		public System.Data.Linq.Table<FD_GROUP> FD_GROUPs
		{
			get
			{
				return this.GetTable<FD_GROUP>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ABBREV")]
	public partial class ABBREV
	{
		
		private string _NDB_No;
		
		private string _Shrt_Desc;
		
		private System.Nullable<double> _Water__g_;
		
		private System.Nullable<double> _Energ_Kcal;
		
		private System.Nullable<double> _Protein__g_;
		
		private System.Nullable<double> _Lipid_Tot__g_;
		
		private System.Nullable<double> _Ash__g_;
		
		private System.Nullable<double> _Carbohydrt__g_;
		
		private System.Nullable<double> _Fiber_TD__g_;
		
		private System.Nullable<double> _Sugar_Tot__g_;
		
		private System.Nullable<double> _Calcium__mg_;
		
		private System.Nullable<double> _Iron__mg_;
		
		private System.Nullable<double> _Magnesium__mg_;
		
		private System.Nullable<double> _Phosphorus__mg_;
		
		private System.Nullable<double> _Potassium__mg_;
		
		private System.Nullable<double> _Sodium__mg_;
		
		private System.Nullable<double> _Zinc__mg_;
		
		private System.Nullable<double> _Copper_mg_;
		
		private System.Nullable<double> _Manganese__mg_;
		
		private System.Nullable<double> _Selenium__µg_;
		
		private System.Nullable<double> _Vit_C__mg_;
		
		private System.Nullable<double> _Thiamin__mg_;
		
		private System.Nullable<double> _Riboflavin__mg_;
		
		private System.Nullable<double> _Niacin__mg_;
		
		private System.Nullable<double> _Panto_Acid_mg_;
		
		private System.Nullable<double> _Vit_B6__mg_;
		
		private System.Nullable<double> _Folate_Tot__µg_;
		
		private System.Nullable<double> _Folic_Acid__µg_;
		
		private System.Nullable<double> _Food_Folate__µg_;
		
		private System.Nullable<double> _Folate_DFE__µg_;
		
		private System.Nullable<double> _Choline_Tot___mg_;
		
		private System.Nullable<double> _Vit_B12__µg_;
		
		private System.Nullable<double> _Vit_A_IU;
		
		private System.Nullable<double> _Vit_A_RAE;
		
		private System.Nullable<double> _Retinol__µg_;
		
		private System.Nullable<double> _Alpha_Carot__µg_;
		
		private System.Nullable<double> _Beta_Carot__µg_;
		
		private System.Nullable<double> _Beta_Crypt__µg_;
		
		private System.Nullable<double> _Lycopene__µg_;
		
		private System.Nullable<double> _Lut_Zea___µg_;
		
		private System.Nullable<double> _Vit_E__mg_;
		
		private System.Nullable<double> _Vit_D_µg;
		
		private System.Nullable<double> _ViVit_D_IU;
		
		private System.Nullable<double> _Vit_K___µg_;
		
		private System.Nullable<double> _FA_Sat__g_;
		
		private System.Nullable<double> _FA_Mono__g_;
		
		private System.Nullable<double> _FA_Poly__g_;
		
		private System.Nullable<double> _Cholestrl__mg_;
		
		private System.Nullable<double> _GmWt_1;
		
		private string _GmWt_Desc1;
		
		private System.Nullable<double> _GmWt_2;
		
		private string _GmWt_Desc2;
		
		private System.Nullable<double> _Refuse_Pct;
		
		public ABBREV()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NDB_No", DbType="NVarChar(5)")]
		public string NDB_No
		{
			get
			{
				return this._NDB_No;
			}
			set
			{
				if ((this._NDB_No != value))
				{
					this._NDB_No = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Shrt_Desc", DbType="NVarChar(255)")]
		public string Shrt_Desc
		{
			get
			{
				return this._Shrt_Desc;
			}
			set
			{
				if ((this._Shrt_Desc != value))
				{
					this._Shrt_Desc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Water_(g)]", Storage="_Water__g_", DbType="Float")]
		public System.Nullable<double> Water__g_
		{
			get
			{
				return this._Water__g_;
			}
			set
			{
				if ((this._Water__g_ != value))
				{
					this._Water__g_ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Energ_Kcal", DbType="Float")]
		public System.Nullable<double> Energ_Kcal
		{
			get
			{
				return this._Energ_Kcal;
			}
			set
			{
				if ((this._Energ_Kcal != value))
				{
					this._Energ_Kcal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Protein_(g)]", Storage="_Protein__g_", DbType="Float")]
		public System.Nullable<double> Protein__g_
		{
			get
			{
				return this._Protein__g_;
			}
			set
			{
				if ((this._Protein__g_ != value))
				{
					this._Protein__g_ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Lipid_Tot_(g)]", Storage="_Lipid_Tot__g_", DbType="Float")]
		public System.Nullable<double> Lipid_Tot__g_
		{
			get
			{
				return this._Lipid_Tot__g_;
			}
			set
			{
				if ((this._Lipid_Tot__g_ != value))
				{
					this._Lipid_Tot__g_ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Ash_(g)]", Storage="_Ash__g_", DbType="Float")]
		public System.Nullable<double> Ash__g_
		{
			get
			{
				return this._Ash__g_;
			}
			set
			{
				if ((this._Ash__g_ != value))
				{
					this._Ash__g_ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Carbohydrt_(g)]", Storage="_Carbohydrt__g_", DbType="Float")]
		public System.Nullable<double> Carbohydrt__g_
		{
			get
			{
				return this._Carbohydrt__g_;
			}
			set
			{
				if ((this._Carbohydrt__g_ != value))
				{
					this._Carbohydrt__g_ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Fiber_TD_(g)]", Storage="_Fiber_TD__g_", DbType="Float")]
		public System.Nullable<double> Fiber_TD__g_
		{
			get
			{
				return this._Fiber_TD__g_;
			}
			set
			{
				if ((this._Fiber_TD__g_ != value))
				{
					this._Fiber_TD__g_ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Sugar_Tot_(g)]", Storage="_Sugar_Tot__g_", DbType="Float")]
		public System.Nullable<double> Sugar_Tot__g_
		{
			get
			{
				return this._Sugar_Tot__g_;
			}
			set
			{
				if ((this._Sugar_Tot__g_ != value))
				{
					this._Sugar_Tot__g_ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Calcium_(mg)]", Storage="_Calcium__mg_", DbType="Float")]
		public System.Nullable<double> Calcium__mg_
		{
			get
			{
				return this._Calcium__mg_;
			}
			set
			{
				if ((this._Calcium__mg_ != value))
				{
					this._Calcium__mg_ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Iron_(mg)]", Storage="_Iron__mg_", DbType="Float")]
		public System.Nullable<double> Iron__mg_
		{
			get
			{
				return this._Iron__mg_;
			}
			set
			{
				if ((this._Iron__mg_ != value))
				{
					this._Iron__mg_ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Magnesium_(mg)]", Storage="_Magnesium__mg_", DbType="Float")]
		public System.Nullable<double> Magnesium__mg_
		{
			get
			{
				return this._Magnesium__mg_;
			}
			set
			{
				if ((this._Magnesium__mg_ != value))
				{
					this._Magnesium__mg_ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Phosphorus_(mg)]", Storage="_Phosphorus__mg_", DbType="Float")]
		public System.Nullable<double> Phosphorus__mg_
		{
			get
			{
				return this._Phosphorus__mg_;
			}
			set
			{
				if ((this._Phosphorus__mg_ != value))
				{
					this._Phosphorus__mg_ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Potassium_(mg)]", Storage="_Potassium__mg_", DbType="Float")]
		public System.Nullable<double> Potassium__mg_
		{
			get
			{
				return this._Potassium__mg_;
			}
			set
			{
				if ((this._Potassium__mg_ != value))
				{
					this._Potassium__mg_ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Sodium_(mg)]", Storage="_Sodium__mg_", DbType="Float")]
		public System.Nullable<double> Sodium__mg_
		{
			get
			{
				return this._Sodium__mg_;
			}
			set
			{
				if ((this._Sodium__mg_ != value))
				{
					this._Sodium__mg_ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Zinc_(mg)]", Storage="_Zinc__mg_", DbType="Float")]
		public System.Nullable<double> Zinc__mg_
		{
			get
			{
				return this._Zinc__mg_;
			}
			set
			{
				if ((this._Zinc__mg_ != value))
				{
					this._Zinc__mg_ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Copper_mg)]", Storage="_Copper_mg_", DbType="Float")]
		public System.Nullable<double> Copper_mg_
		{
			get
			{
				return this._Copper_mg_;
			}
			set
			{
				if ((this._Copper_mg_ != value))
				{
					this._Copper_mg_ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Manganese_(mg)]", Storage="_Manganese__mg_", DbType="Float")]
		public System.Nullable<double> Manganese__mg_
		{
			get
			{
				return this._Manganese__mg_;
			}
			set
			{
				if ((this._Manganese__mg_ != value))
				{
					this._Manganese__mg_ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Selenium_(µg)]", Storage="_Selenium__µg_", DbType="Float")]
		public System.Nullable<double> Selenium__µg_
		{
			get
			{
				return this._Selenium__µg_;
			}
			set
			{
				if ((this._Selenium__µg_ != value))
				{
					this._Selenium__µg_ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Vit_C_(mg)]", Storage="_Vit_C__mg_", DbType="Float")]
		public System.Nullable<double> Vit_C__mg_
		{
			get
			{
				return this._Vit_C__mg_;
			}
			set
			{
				if ((this._Vit_C__mg_ != value))
				{
					this._Vit_C__mg_ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Thiamin_(mg)]", Storage="_Thiamin__mg_", DbType="Float")]
		public System.Nullable<double> Thiamin__mg_
		{
			get
			{
				return this._Thiamin__mg_;
			}
			set
			{
				if ((this._Thiamin__mg_ != value))
				{
					this._Thiamin__mg_ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Riboflavin_(mg)]", Storage="_Riboflavin__mg_", DbType="Float")]
		public System.Nullable<double> Riboflavin__mg_
		{
			get
			{
				return this._Riboflavin__mg_;
			}
			set
			{
				if ((this._Riboflavin__mg_ != value))
				{
					this._Riboflavin__mg_ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Niacin_(mg)]", Storage="_Niacin__mg_", DbType="Float")]
		public System.Nullable<double> Niacin__mg_
		{
			get
			{
				return this._Niacin__mg_;
			}
			set
			{
				if ((this._Niacin__mg_ != value))
				{
					this._Niacin__mg_ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Panto_Acid_mg)]", Storage="_Panto_Acid_mg_", DbType="Float")]
		public System.Nullable<double> Panto_Acid_mg_
		{
			get
			{
				return this._Panto_Acid_mg_;
			}
			set
			{
				if ((this._Panto_Acid_mg_ != value))
				{
					this._Panto_Acid_mg_ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Vit_B6_(mg)]", Storage="_Vit_B6__mg_", DbType="Float")]
		public System.Nullable<double> Vit_B6__mg_
		{
			get
			{
				return this._Vit_B6__mg_;
			}
			set
			{
				if ((this._Vit_B6__mg_ != value))
				{
					this._Vit_B6__mg_ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Folate_Tot_(µg)]", Storage="_Folate_Tot__µg_", DbType="Float")]
		public System.Nullable<double> Folate_Tot__µg_
		{
			get
			{
				return this._Folate_Tot__µg_;
			}
			set
			{
				if ((this._Folate_Tot__µg_ != value))
				{
					this._Folate_Tot__µg_ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Folic_Acid_(µg)]", Storage="_Folic_Acid__µg_", DbType="Float")]
		public System.Nullable<double> Folic_Acid__µg_
		{
			get
			{
				return this._Folic_Acid__µg_;
			}
			set
			{
				if ((this._Folic_Acid__µg_ != value))
				{
					this._Folic_Acid__µg_ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Food_Folate_(µg)]", Storage="_Food_Folate__µg_", DbType="Float")]
		public System.Nullable<double> Food_Folate__µg_
		{
			get
			{
				return this._Food_Folate__µg_;
			}
			set
			{
				if ((this._Food_Folate__µg_ != value))
				{
					this._Food_Folate__µg_ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Folate_DFE_(µg)]", Storage="_Folate_DFE__µg_", DbType="Float")]
		public System.Nullable<double> Folate_DFE__µg_
		{
			get
			{
				return this._Folate_DFE__µg_;
			}
			set
			{
				if ((this._Folate_DFE__µg_ != value))
				{
					this._Folate_DFE__µg_ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Choline_Tot_ (mg)]", Storage="_Choline_Tot___mg_", DbType="Float")]
		public System.Nullable<double> Choline_Tot___mg_
		{
			get
			{
				return this._Choline_Tot___mg_;
			}
			set
			{
				if ((this._Choline_Tot___mg_ != value))
				{
					this._Choline_Tot___mg_ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Vit_B12_(µg)]", Storage="_Vit_B12__µg_", DbType="Float")]
		public System.Nullable<double> Vit_B12__µg_
		{
			get
			{
				return this._Vit_B12__µg_;
			}
			set
			{
				if ((this._Vit_B12__µg_ != value))
				{
					this._Vit_B12__µg_ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vit_A_IU", DbType="Float")]
		public System.Nullable<double> Vit_A_IU
		{
			get
			{
				return this._Vit_A_IU;
			}
			set
			{
				if ((this._Vit_A_IU != value))
				{
					this._Vit_A_IU = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vit_A_RAE", DbType="Float")]
		public System.Nullable<double> Vit_A_RAE
		{
			get
			{
				return this._Vit_A_RAE;
			}
			set
			{
				if ((this._Vit_A_RAE != value))
				{
					this._Vit_A_RAE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Retinol_(µg)]", Storage="_Retinol__µg_", DbType="Float")]
		public System.Nullable<double> Retinol__µg_
		{
			get
			{
				return this._Retinol__µg_;
			}
			set
			{
				if ((this._Retinol__µg_ != value))
				{
					this._Retinol__µg_ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Alpha_Carot_(µg)]", Storage="_Alpha_Carot__µg_", DbType="Float")]
		public System.Nullable<double> Alpha_Carot__µg_
		{
			get
			{
				return this._Alpha_Carot__µg_;
			}
			set
			{
				if ((this._Alpha_Carot__µg_ != value))
				{
					this._Alpha_Carot__µg_ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Beta_Carot_(µg)]", Storage="_Beta_Carot__µg_", DbType="Float")]
		public System.Nullable<double> Beta_Carot__µg_
		{
			get
			{
				return this._Beta_Carot__µg_;
			}
			set
			{
				if ((this._Beta_Carot__µg_ != value))
				{
					this._Beta_Carot__µg_ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Beta_Crypt_(µg)]", Storage="_Beta_Crypt__µg_", DbType="Float")]
		public System.Nullable<double> Beta_Crypt__µg_
		{
			get
			{
				return this._Beta_Crypt__µg_;
			}
			set
			{
				if ((this._Beta_Crypt__µg_ != value))
				{
					this._Beta_Crypt__µg_ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Lycopene_(µg)]", Storage="_Lycopene__µg_", DbType="Float")]
		public System.Nullable<double> Lycopene__µg_
		{
			get
			{
				return this._Lycopene__µg_;
			}
			set
			{
				if ((this._Lycopene__µg_ != value))
				{
					this._Lycopene__µg_ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Lut+Zea_ (µg)]", Storage="_Lut_Zea___µg_", DbType="Float")]
		public System.Nullable<double> Lut_Zea___µg_
		{
			get
			{
				return this._Lut_Zea___µg_;
			}
			set
			{
				if ((this._Lut_Zea___µg_ != value))
				{
					this._Lut_Zea___µg_ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Vit_E_(mg)]", Storage="_Vit_E__mg_", DbType="Float")]
		public System.Nullable<double> Vit_E__mg_
		{
			get
			{
				return this._Vit_E__mg_;
			}
			set
			{
				if ((this._Vit_E__mg_ != value))
				{
					this._Vit_E__mg_ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vit_D_µg", DbType="Float")]
		public System.Nullable<double> Vit_D_µg
		{
			get
			{
				return this._Vit_D_µg;
			}
			set
			{
				if ((this._Vit_D_µg != value))
				{
					this._Vit_D_µg = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ViVit_D_IU", DbType="Float")]
		public System.Nullable<double> ViVit_D_IU
		{
			get
			{
				return this._ViVit_D_IU;
			}
			set
			{
				if ((this._ViVit_D_IU != value))
				{
					this._ViVit_D_IU = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Vit_K_*(µg)]", Storage="_Vit_K___µg_", DbType="Float")]
		public System.Nullable<double> Vit_K___µg_
		{
			get
			{
				return this._Vit_K___µg_;
			}
			set
			{
				if ((this._Vit_K___µg_ != value))
				{
					this._Vit_K___µg_ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[FA_Sat_(g)]", Storage="_FA_Sat__g_", DbType="Float")]
		public System.Nullable<double> FA_Sat__g_
		{
			get
			{
				return this._FA_Sat__g_;
			}
			set
			{
				if ((this._FA_Sat__g_ != value))
				{
					this._FA_Sat__g_ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[FA_Mono_(g)]", Storage="_FA_Mono__g_", DbType="Float")]
		public System.Nullable<double> FA_Mono__g_
		{
			get
			{
				return this._FA_Mono__g_;
			}
			set
			{
				if ((this._FA_Mono__g_ != value))
				{
					this._FA_Mono__g_ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[FA_Poly_(g)]", Storage="_FA_Poly__g_", DbType="Float")]
		public System.Nullable<double> FA_Poly__g_
		{
			get
			{
				return this._FA_Poly__g_;
			}
			set
			{
				if ((this._FA_Poly__g_ != value))
				{
					this._FA_Poly__g_ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Cholestrl_(mg)]", Storage="_Cholestrl__mg_", DbType="Float")]
		public System.Nullable<double> Cholestrl__mg_
		{
			get
			{
				return this._Cholestrl__mg_;
			}
			set
			{
				if ((this._Cholestrl__mg_ != value))
				{
					this._Cholestrl__mg_ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GmWt_1", DbType="Float")]
		public System.Nullable<double> GmWt_1
		{
			get
			{
				return this._GmWt_1;
			}
			set
			{
				if ((this._GmWt_1 != value))
				{
					this._GmWt_1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GmWt_Desc1", DbType="NVarChar(255)")]
		public string GmWt_Desc1
		{
			get
			{
				return this._GmWt_Desc1;
			}
			set
			{
				if ((this._GmWt_Desc1 != value))
				{
					this._GmWt_Desc1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GmWt_2", DbType="Float")]
		public System.Nullable<double> GmWt_2
		{
			get
			{
				return this._GmWt_2;
			}
			set
			{
				if ((this._GmWt_2 != value))
				{
					this._GmWt_2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GmWt_Desc2", DbType="NVarChar(255)")]
		public string GmWt_Desc2
		{
			get
			{
				return this._GmWt_Desc2;
			}
			set
			{
				if ((this._GmWt_Desc2 != value))
				{
					this._GmWt_Desc2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Refuse_Pct", DbType="Float")]
		public System.Nullable<double> Refuse_Pct
		{
			get
			{
				return this._Refuse_Pct;
			}
			set
			{
				if ((this._Refuse_Pct != value))
				{
					this._Refuse_Pct = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.WEIGHT")]
	public partial class WEIGHT
	{
		
		private string _NDB_No;
		
		private string _Seq;
		
		private System.Nullable<double> _Amount;
		
		private string _Msre_Desc;
		
		private System.Nullable<double> _Gm_Wgt;
		
		private System.Nullable<short> _Num_Data_Pts;
		
		public WEIGHT()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NDB_No", DbType="NVarChar(5)")]
		public string NDB_No
		{
			get
			{
				return this._NDB_No;
			}
			set
			{
				if ((this._NDB_No != value))
				{
					this._NDB_No = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Seq", DbType="NVarChar(2)")]
		public string Seq
		{
			get
			{
				return this._Seq;
			}
			set
			{
				if ((this._Seq != value))
				{
					this._Seq = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Amount", DbType="Float")]
		public System.Nullable<double> Amount
		{
			get
			{
				return this._Amount;
			}
			set
			{
				if ((this._Amount != value))
				{
					this._Amount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Msre_Desc", DbType="NVarChar(84)")]
		public string Msre_Desc
		{
			get
			{
				return this._Msre_Desc;
			}
			set
			{
				if ((this._Msre_Desc != value))
				{
					this._Msre_Desc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gm_Wgt", DbType="Float")]
		public System.Nullable<double> Gm_Wgt
		{
			get
			{
				return this._Gm_Wgt;
			}
			set
			{
				if ((this._Gm_Wgt != value))
				{
					this._Gm_Wgt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Num_Data_Pts", DbType="SmallInt")]
		public System.Nullable<short> Num_Data_Pts
		{
			get
			{
				return this._Num_Data_Pts;
			}
			set
			{
				if ((this._Num_Data_Pts != value))
				{
					this._Num_Data_Pts = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.FOOD_DES")]
	public partial class FOOD_DE
	{
		
		private string _NDB_No;
		
		private string _FdGrp_Cd;
		
		private string _Long_Desc;
		
		private string _Shrt_Desc;
		
		private string _ComName;
		
		private string _ManufacName;
		
		private string _Survey;
		
		private string _Ref_Desc;
		
		private System.Nullable<short> _Refuse;
		
		private string _SciName;
		
		private System.Nullable<float> _N_Factor;
		
		private System.Nullable<float> _Pro_Factor;
		
		private System.Nullable<float> _Fat_Factor;
		
		private System.Nullable<float> _CHO_Factor;
		
		public FOOD_DE()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NDB_No", DbType="NVarChar(5)")]
		public string NDB_No
		{
			get
			{
				return this._NDB_No;
			}
			set
			{
				if ((this._NDB_No != value))
				{
					this._NDB_No = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FdGrp_Cd", DbType="NVarChar(4)")]
		public string FdGrp_Cd
		{
			get
			{
				return this._FdGrp_Cd;
			}
			set
			{
				if ((this._FdGrp_Cd != value))
				{
					this._FdGrp_Cd = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Long_Desc", DbType="NVarChar(200)")]
		public string Long_Desc
		{
			get
			{
				return this._Long_Desc;
			}
			set
			{
				if ((this._Long_Desc != value))
				{
					this._Long_Desc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Shrt_Desc", DbType="NVarChar(60)")]
		public string Shrt_Desc
		{
			get
			{
				return this._Shrt_Desc;
			}
			set
			{
				if ((this._Shrt_Desc != value))
				{
					this._Shrt_Desc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ComName", DbType="NVarChar(100)")]
		public string ComName
		{
			get
			{
				return this._ComName;
			}
			set
			{
				if ((this._ComName != value))
				{
					this._ComName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ManufacName", DbType="NVarChar(65)")]
		public string ManufacName
		{
			get
			{
				return this._ManufacName;
			}
			set
			{
				if ((this._ManufacName != value))
				{
					this._ManufacName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Survey", DbType="NVarChar(1)")]
		public string Survey
		{
			get
			{
				return this._Survey;
			}
			set
			{
				if ((this._Survey != value))
				{
					this._Survey = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ref_Desc", DbType="NVarChar(135)")]
		public string Ref_Desc
		{
			get
			{
				return this._Ref_Desc;
			}
			set
			{
				if ((this._Ref_Desc != value))
				{
					this._Ref_Desc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Refuse", DbType="SmallInt")]
		public System.Nullable<short> Refuse
		{
			get
			{
				return this._Refuse;
			}
			set
			{
				if ((this._Refuse != value))
				{
					this._Refuse = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SciName", DbType="NVarChar(65)")]
		public string SciName
		{
			get
			{
				return this._SciName;
			}
			set
			{
				if ((this._SciName != value))
				{
					this._SciName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_N_Factor", DbType="Real")]
		public System.Nullable<float> N_Factor
		{
			get
			{
				return this._N_Factor;
			}
			set
			{
				if ((this._N_Factor != value))
				{
					this._N_Factor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pro_Factor", DbType="Real")]
		public System.Nullable<float> Pro_Factor
		{
			get
			{
				return this._Pro_Factor;
			}
			set
			{
				if ((this._Pro_Factor != value))
				{
					this._Pro_Factor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fat_Factor", DbType="Real")]
		public System.Nullable<float> Fat_Factor
		{
			get
			{
				return this._Fat_Factor;
			}
			set
			{
				if ((this._Fat_Factor != value))
				{
					this._Fat_Factor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHO_Factor", DbType="Real")]
		public System.Nullable<float> CHO_Factor
		{
			get
			{
				return this._CHO_Factor;
			}
			set
			{
				if ((this._CHO_Factor != value))
				{
					this._CHO_Factor = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.FD_GROUP")]
	public partial class FD_GROUP
	{
		
		private string _FdGrp_CD;
		
		private string _FdGrp_Desc;
		
		public FD_GROUP()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FdGrp_CD", DbType="NVarChar(5)")]
		public string FdGrp_CD
		{
			get
			{
				return this._FdGrp_CD;
			}
			set
			{
				if ((this._FdGrp_CD != value))
				{
					this._FdGrp_CD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FdGrp_Desc", DbType="NVarChar(60)")]
		public string FdGrp_Desc
		{
			get
			{
				return this._FdGrp_Desc;
			}
			set
			{
				if ((this._FdGrp_Desc != value))
				{
					this._FdGrp_Desc = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
