// <auto-generated />
namespace ShoppingNut.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class MoreFoodInfo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MoreFoodInfo));
        
        string IMigrationMetadata.Id
        {
            get { return "201310092330584_MoreFoodInfo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
