// <auto-generated />
namespace ShoppingNut.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class blah : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(blah));
        
        string IMigrationMetadata.Id
        {
            get { return "201307261927242_blah"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
